'use strict';
// 添加角色时，复制一个对象并更换唯一 id。图片也可改为 ./images/haanye.webp。
const characters = [
 {id:'haanye',name:'幻叶',en:'Haanye',tag:'Green Leaf Dream',group:'forest',personality:'活泼 / 开朗 / 温柔',birthday:'11月23日 · 初春之叶',quote:'像风一样，把快乐吹进每一片叶子里。',story:'幻叶诞生于初春嫩芽萌发的瞬间，身着荧光嫩绿的潮流外套。她热爱踏着晨曦露水漫游在各地森林，把收集落叶作为独一无二的宝物。那双清澈的眼睛闪烁着自然的生机，把风的温度带给旅途中的每个人。',image:'https://picui.ogmua.cn/s1/2026/09/13/6aa6a9fba2fc6.webp',freq:523.25},
 {id:'xiaoyezi',name:'小叶子',en:'Xiaoyezi',tag:'Pure Natural',group:'forest',personality:'温柔 / 腼腆 / 细腻',birthday:'10月12日 · 碧水微澜',quote:'一片叶子，一份温柔。很高兴认识你~',story:'小叶子宛如春日微风拂落的柔光。坐在石栏旁的她总是安静翻阅着画册，青翠长发旁缀着两片嫩芽发饰。她虽然不善张扬言语，却能用最纯净的目光与无声陪伴，治愈每一个平凡疲惫的日常。',image:'https://picui.ogmua.cn/s1/2026/09/13/6aa6acb082068.webp',freq:587.33},
 {id:'twins',name:'小白 & 小黑',en:'Little Black & White',tag:'Two Souls, One World',group:'cats',personality:'小白（软萌傲娇）· 小黑（活泼粘人）',birthday:'双生同栖 · 永恒晨曦',quote:'有你在的地方，就是最温暖的角落 ♡',story:'依偎在暖阳里的猫耳双生少女。戴着十字发夹的白猫小白略带害羞，黑猫小黑则总是开心地紧紧环抱对方。黑白相依，是彼此无可替代的纯洁羁绊，在安静的角落构筑起最坚实的避风港。',image:'https://picui.ogmua.cn/s1/2026/09/13/6aa6ae2bbc8c3.webp',freq:659.25},
 {id:'daidai',name:'呆呆',en:'Daidai',tag:'Big Dreamer',group:'cats',personality:'天真 / 呆萌 / 温柔',birthday:'猫尾星纪 · 晴空倒影',quote:'虽然有点呆，但我一直都在努力变可爱！',story:'拥有一头如澄澈海浪般微卷蓝发的猫尾女孩呆呆。戴着宽大的魔法兜帽，脚踩厚底运动鞋坐在水镜倒影中。她是一个很普通但又无比特别的小小存在，时刻期待着与你一同出发去看更大的世界。',image:'https://picui.ogmua.cn/s1/2026/09/13/6aa6ad2c1965f.webp',freq:783.99}
];
const app=document.querySelector('#app');
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let favorites=new Set();
try{const saved=JSON.parse(localStorage.getItem('aetheria-favorites')||'[]');if(Array.isArray(saved)) favorites=new Set(saved.filter(id=>characters.some(c=>c.id===id)));}catch{}
let audio, soundOn=false, noticeTimer, filter='all', query='';
function notice(message){const n=document.querySelector('#notice');n.textContent=message;n.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('show'),2500);}
function tone(freq){if(!soundOn||!audio)return;try{audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.22);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.23);}catch{}}
document.querySelector('#sound').addEventListener('click',async e=>{const button=e.currentTarget;try{if(!audio){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error();audio=new Audio();}await audio.resume();soundOn=!soundOn;button.textContent=`音效：${soundOn?'开':'关'}`;button.setAttribute('aria-pressed',String(soundOn));tone(523.25);}catch{notice('此浏览器暂不支持音效');}});
function heart(c){return `<button class="heart" data-save="${c.id}" aria-pressed="${favorites.has(c.id)}" aria-label="${favorites.has(c.id)?'取消收藏':'收藏'}${escapeHTML(c.name)}">${favorites.has(c.id)?'♥':'♡'}</button>`;}
function card(c){return `<article class="card"><a href="#character/${c.id}" aria-label="查看${escapeHTML(c.name)}"><div class="card-art"><img src="${escapeHTML(c.image)}" alt="${escapeHTML(c.name)}的角色立绘" loading="lazy"><span class="badge">${escapeHTML(c.tag)}</span></div></a><div class="card-body"><h3>${escapeHTML(c.name)}</h3><small>${escapeHTML(c.en)}</small><p>“${escapeHTML(c.quote)}”</p><div class="card-foot"><a href="#character/${c.id}">展开物语 ↗</a>${heart(c)}</div></div></article>`;}
function intro(en,title,desc){return `<div class="intro"><p class="eyebrow">${en}</p><h1>${title}</h1><p class="lead">${desc}</p></div>`;}
function home(){const c=characters[0];return `<section class="hero"><div><p class="eyebrow">A little leaf, a whole universe</p><h1 class="hero-title">让每一次相遇，<br>都长出<em>温柔。</em></h1><p class="lead">70% 灵动羁绊，30% 幻境微风。<br>欢迎来到萌叶幻想物语，收藏属于你的心动瞬间。</p><div class="actions"><a class="button" href="#gallery">开启相遇 →</a><button class="button secondary" data-random>随缘邂逅 ✧</button></div></div><a class="hero-art" href="#character/haanye"><img src="${c.image}" alt="幻叶" fetchpriority="high"><div class="hero-caption"><div><small>本期邂逅 · 01</small><h3>幻叶 / Haanye</h3></div><span>↗</span></div></a></section><div class="section-heading"><h2>风带来的朋友</h2><a href="#gallery">查看全部 →</a></div><div class="grid">${characters.map(card).join('')}</div><section class="quote-banner"><small>LET THE STORY BEGIN</small><p>一片叶子，也可以藏着一整个世界。</p><a href="#world">走进幻想之境 ↗</a></section>`;}
function gallery(){return intro('Character archive','角色图鉴','在不同的颜色与性格里，找到与你共鸣的她。')+`<label class="muted" for="search">寻找角色</label><input id="search" class="search" type="search" placeholder="搜索名字、性格或物语…" value="${escapeHTML(query)}"><div class="toolbar" aria-label="角色分类">${[['all','全部角色'],['forest','森林来信'],['cats','猫尾星光']].map(([id,label])=>`<button class="chip" data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div><p id="result-count" class="count" role="status"></p><div id="results" class="grid"></div>`;}
function updateResults(){const list=characters.filter(c=>(filter==='all'||c.group===filter)&&`${c.name} ${c.en} ${c.personality} ${c.story}`.toLowerCase().includes(query.trim().toLowerCase()));document.querySelector('#results').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><h2>风暂时没有带来回音</h2><p>换个关键词，或者选择全部角色试试。</p></div>';document.querySelector('#result-count').textContent=`找到 ${list.length} 组角色`;}
// 以下世界地点是基于原角色故事新增的可修改设定。
function world(){return intro('The world of Aetheria','世界的温柔切面','沿着叶脉、微光与水面，寻找故事开始的地方。')+`<div class="world-grid">${[
 ['❧','01 / 初芽之森','清晨的露水尚未散去，幻叶已经踏上收集落叶的旅程。这里的每一阵风，都会替旅人捎来一份快乐。','haanye','和幻叶去散步'],
 ['◌','02 / 碧水庭院','石栏、画册与安静的午后。小叶子在这里留了一处空位，等待愿意慢慢听风的朋友。','xiaoyezi','坐在小叶子身旁'],
 ['☼','03 / 双生暖阁','阳光落在窗边，黑与白依偎成一个小小世界。有彼此陪伴，平凡的一天也会闪闪发亮。','twins','拜访双生少女'],
 ['✧','04 / 晴空水镜','天空映进澄澈的水里，呆呆把一个个大梦想悄悄装进兜帽。下一站，会是怎样的风景？','daidai','与呆呆一起出发']
 ].map(([symbol,title,text,id,link])=>`<article class="panel"><div class="world-symbol" aria-hidden="true">${symbol}</div><h2>${title}</h2><p>${text}</p><a href="#character/${id}">${link} →</a></article>`).join('')}</div><section class="quote-banner"><small>OUR LITTLE PHILOSOPHY</small><p>不必成为谁的光，也可以慢慢发芽。</p><span class="muted">每一个普通又特别的你，都值得被温柔以待。</span></section>`;}
function collection(){const list=characters.filter(c=>favorites.has(c.id));return intro('My little collection','我的心动收藏','把喜欢留在这里，下次相遇就不必寻找。')+`<p class="count">已收藏 ${list.length} / ${characters.length} 组角色 · 收藏保存在当前浏览器</p><div class="grid">${list.length?list.map(card).join(''):'<section class="empty"><h2>还没有收藏的朋友</h2><p>点击角色卡片上的 ♡，留住第一次心动。</p><a class="button" href="#gallery">去图鉴逛逛 →</a></section>'}</div>`;}
function detail(id){const c=characters.find(c=>c.id===id);if(!c)return intro('Lost in the wind','这位朋友还没有到来','角色链接可能有误。')+'<a class="button" href="#gallery">返回图鉴</a>';return `<a class="quiet" href="#gallery">← 返回角色图鉴</a><section class="detail"><figure class="full-art" id="swipe-area"><img src="${escapeHTML(c.image)}" alt="${escapeHTML(c.name)}完整立绘"><figcaption>原比例完整展示 · 左右轻扫切换角色</figcaption></figure><div class="detail-info"><p class="eyebrow">${escapeHTML(c.tag)}</p><h1>${escapeHTML(c.name)}</h1><p class="en-name">${escapeHTML(c.en)}</p><div class="actions"><button class="button" data-save="${c.id}" aria-pressed="${favorites.has(c.id)}">${favorites.has(c.id)?'♥ 已收藏':'♡ 收藏这位角色'}</button><button class="quiet" data-share>复制角色链接 ↗</button></div><div class="meta"><div class="panel"><small>PERSONALITY / 性格</small>${escapeHTML(c.personality)}</div><div class="panel"><small>BIRTHDAY / 诞生印记</small>${escapeHTML(c.birthday)}</div></div><article class="panel story"><p class="eyebrow">THE LITTLE STORY</p><h2>“${escapeHTML(c.quote)}”</h2><p>${escapeHTML(c.story)}</p></article><div class="switcher"><button class="quiet" data-step="-1">← 上一位</button><button class="quiet" data-step="1">下一位 →</button></div><small>也可以使用键盘 ← → 切换，Esc 返回图鉴。</small></div></section>`;}
function current(){return location.hash.slice(1)||'home';}
function render(moveFocus=false){const route=current(),page=route.split('/')[0];app.innerHTML=page==='character'?detail(route.split('/')[1]):page==='gallery'?gallery():page==='world'?world():page==='favorites'?collection():page==='home'?home():intro('Lost in the wind','这条小路还未开放','请使用下方导航继续探索。');if(page==='gallery')updateResults();app.insertAdjacentHTML('beforeend','<footer class="footer-note">AETHERIA · 愿每一片叶子，都被温柔收藏</footer>');document.querySelectorAll('.navigation a').forEach(a=>{if(a.hash==='#'+(page==='character'?'gallery':page))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const c=characters.find(c=>'character/'+c.id===route);document.title=`${c?c.name:({home:'首页',gallery:'角色图鉴',world:'幻想世界',favorites:'我的收藏'}[page]||'未找到')} · 萌叶幻想物语`;bindSwipe();if(moveFocus){window.scrollTo(0,0);app.focus({preventScroll:true});}if(c)tone(c.freq);}
function toggleSave(id){if(!characters.some(c=>c.id===id))return;favorites.has(id)?favorites.delete(id):favorites.add(id);let stored=true;try{localStorage.setItem('aetheria-favorites',JSON.stringify([...favorites]));}catch{stored=false;}if(current()==='favorites'){const focused=document.activeElement;const index=[...app.querySelectorAll('[data-save]')].indexOf(focused);render();const next=app.querySelectorAll('[data-save]')[Math.max(0,Math.min(index,favorites.size-1))];(next||app).focus();}else{app.querySelectorAll('[data-save]').forEach(b=>{const c=characters.find(x=>x.id===b.dataset.save),saved=favorites.has(c.id);b.setAttribute('aria-pressed',String(saved));b.textContent=b.classList.contains('heart')?(saved?'♥':'♡'):(saved?'♥ 已收藏':'♡ 收藏这位角色');b.setAttribute('aria-label',`${saved?'取消收藏':'收藏'}${c.name}`);});}notice(stored?(favorites.has(id)?'已放进心动收藏':'已取消收藏'):'当前无法保存，下次打开可能丢失收藏');}
function step(n){const index=characters.findIndex(c=>'character/'+c.id===current());if(index>=0)location.hash='character/'+characters[(index+n+characters.length)%characters.length].id;}
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.save)toggleSave(b.dataset.save);if(b.hasAttribute('data-random'))location.hash='character/'+characters[Math.floor(Math.random()*characters.length)].id;if(b.dataset.step)step(Number(b.dataset.step));if(b.dataset.filter){filter=b.dataset.filter;app.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.filter===filter)));updateResults();}if(b.hasAttribute('data-share')){try{await navigator.clipboard.writeText(location.href);notice('角色链接已复制');}catch{window.prompt('长按下方链接复制',location.href);}}});
app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;updateResults();}});
// 图片外链失效时仍然显示角色文字；错误不会导致页面空白。
app.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const hint=document.createElement('div');hint.className='broken';hint.textContent=e.target.alt+' · 图片暂未加载，请稍后刷新';e.target.replaceWith(hint);}},true);
function bindSwipe(){const area=document.querySelector('#swipe-area');if(!area)return;let start;area.addEventListener('touchstart',e=>{start=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null;},{passive:true});area.addEventListener('touchmove',e=>{if(e.touches.length!==1)start=null;},{passive:true});area.addEventListener('touchcancel',()=>start=null,{passive:true});area.addEventListener('touchend',e=>{if(!start||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;start=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*2)step(dx<0?1:-1);},{passive:true});}
window.addEventListener('keydown',e=>{if(!current().startsWith('character/'))return;if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='Escape')location.hash='gallery';});
window.addEventListener('hashchange',()=>render(true));
window.addEventListener('storage',e=>{if(e.key==='aetheria-favorites'||e.key===null){try{const saved=JSON.parse(localStorage.getItem('aetheria-favorites')||'[]');favorites=new Set(Array.isArray(saved)?saved.filter(id=>characters.some(c=>c.id===id)):[]);render();}catch{}}});
render();
