'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], chars=window.CHARACTERS;
const storage={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{notify('浏览器未允许本地保存，本次会话仍可使用。');return false}}};
let favorites=storage.get('qingjian-favorites',[]);if(!Array.isArray(favorites))favorites=[];
let prefs=storage.get('qingjian-prefs',{});if(!prefs||typeof prefs!=='object')prefs={};
let current=chars[0],index=0,viewerIndex=0,toastTimer,motion=false,motionTimer,frame=0,origin=null;
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const src=file=>'./assets/'+encodeURIComponent(file);
function notify(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function setPrefs(){document.body.classList.toggle('night',!!prefs.night);document.body.classList.toggle('large',!!prefs.large);document.body.classList.toggle('no-motion',!!prefs.still);if(prefs.still||reduce.matches)stopMotion();storage.set('qingjian-prefs',prefs)}
function favoriteUI(){const yes=favorites.includes(current.id);$('#favorite').textContent=yes?'♥':'♡';$('#favorite').setAttribute('aria-pressed',yes);$('#favorite').setAttribute('aria-label',yes?'取消收藏角色':'收藏角色');$('#mobile-favorite').textContent=yes?'♥ 已收藏':'♡ 收藏角色';$('#count').textContent=favorites.length}
function toggleFavorite(){favorites=favorites.includes(current.id)?favorites.filter(id=>id!==current.id):[...favorites,current.id];storage.set('qingjian-favorites',favorites);favoriteUI()}
$('#characters').innerHTML=chars.map(c=>`<button role="tab" id="character-${c.id}" aria-controls="character-panel" data-id="${c.id}" aria-selected="false" tabindex="-1"><img src="${src(c.images[0][0])}" alt=""><span>${c.name}</span></button>`).join('');
function select(id){current=chars.find(c=>c.id===id)||chars[0];index=0;document.documentElement.style.setProperty('--accent',current.color);document.documentElement.style.setProperty('--tint',current.tint);['name','subtitle','mood','quote','story'].forEach(k=>$('#'+k).textContent=current[k]);$('#tags').innerHTML=current.tags.map(t=>`<span>${t}</span>`).join('');$('#details').innerHTML=Object.entries(current.details).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');$('#character-panel').setAttribute('aria-labelledby','character-'+current.id);$$('#characters button').forEach(b=>{const yes=b.dataset.id===current.id;b.setAttribute('aria-selected',yes);b.tabIndex=yes?0:-1});$('#character-'+current.id).scrollIntoView({block:'nearest',inline:'nearest'});$('#gallery-desc').textContent=`${current.images.length} 幅作品，收好每一种心情。`;$('#gallery').innerHTML=current.images.map(([file,title],i)=>`<button data-image="${i}" aria-label="鉴赏：${title}"><img loading="lazy" src="${src(file)}" alt="${title}"><span>${title}<small>打开原图</small></span></button>`).join('');document.title=current.name+' · 晴间来信';favoriteUI();showImage();showPane('story');if($('#viewer').open){viewerIndex=0;updateViewer()}}
function showImage(){const [file,title]=current.images[index];$('.image-error').hidden=true;$('#hero').src=src(file);$('#hero').alt=title;$('#scene').textContent=title;$('#image-count').textContent=`${String(index+1).padStart(2,'0')} / ${String(current.images.length).padStart(2,'0')}  ·  ${current.name}的光影`;$('#prev').disabled=$('#next').disabled=current.images.length<2}
function moveImage(n){index=(index+n+current.images.length)%current.images.length;showImage()}
$('#hero').onerror=()=>$('.image-error').hidden=false;$('#hero').onload=()=>$('.image-error').hidden=true;$('#retry').onclick=()=>{const url=src(current.images[index][0]);$('#hero').src=url+'?retry='+Date.now()};
$('#characters').onclick=e=>{const b=e.target.closest('[data-id]');if(b)location.hash=b.dataset.id};window.addEventListener('hashchange',()=>select(location.hash.slice(1)));
function tabKeys(container,activate){container.addEventListener('keydown',e=>{const items=[...container.querySelectorAll('[role=tab]')];const i=items.indexOf(document.activeElement);if(i<0)return;let n;if(e.key==='ArrowRight')n=(i+1)%items.length;else if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=items.length-1;else return;e.preventDefault();items[n].focus();activate(items[n])})}
tabKeys($('#characters'),b=>location.hash=b.dataset.id);tabKeys($('.content-tabs'),b=>showPane(b.dataset.pane));
function showPane(name){$$('.content-tabs button').forEach(b=>{const yes=b.dataset.pane===name;b.setAttribute('aria-selected',yes);b.tabIndex=yes?0:-1});$$('.pane').forEach(p=>p.hidden=p.id!=='pane-'+name)}
$('.content-tabs').onclick=e=>{const b=e.target.closest('[data-pane]');if(b)showPane(b.dataset.pane)};
$('#favorite').onclick=$('#mobile-favorite').onclick=toggleFavorite;$('#prev').onclick=()=>moveImage(-1);$('#next').onclick=()=>moveImage(1);
function updateViewer(){const [file,title]=current.images[viewerIndex];$('#viewer-img').src=src(file);$('#viewer-img').alt=title;$('#viewer-title').textContent=title;$('#viewer-count').textContent=`${viewerIndex+1} / ${current.images.length}`;$('#download').href=src(file);$('#download').download=file;$('#viewer-prev').disabled=$('#viewer-next').disabled=current.images.length<2;$('#viewer-area').classList.remove('zoomed');$('#zoom').textContent='放大'}
function openViewer(i=index){viewerIndex=i;updateViewer();if(!$('#viewer').open)$('#viewer').showModal()}
function moveViewer(n){viewerIndex=(viewerIndex+n+current.images.length)%current.images.length;updateViewer()}
$('#open-art').onclick=$('#mobile-art').onclick=()=>openViewer();$('#show-gallery').onclick=()=>openViewer(0);$('#gallery').onclick=e=>{const b=e.target.closest('[data-image]');if(b)openViewer(Number(b.dataset.image))};$('#close-viewer').onclick=()=>$('#viewer').close();$('#viewer-prev').onclick=()=>moveViewer(-1);$('#viewer-next').onclick=()=>moveViewer(1);$('#zoom').onclick=()=>{$('#viewer-area').classList.toggle('zoomed');$('#zoom').textContent=$('#viewer-area').classList.contains('zoomed')?'适合屏幕':'放大'};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#viewer').requestFullscreen)await $('#viewer').requestFullscreen();else notify('当前浏览器不支持全屏，已使用沉浸鉴赏。')}catch{notify('未能进入全屏，可以继续使用沉浸鉴赏。')}};$('#viewer').addEventListener('close',()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})});
function swipe(el,fn){let start;el.addEventListener('touchstart',e=>{if(e.touches.length!==1){start=null;return}start=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});el.addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];start=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.7)fn(dx<0?1:-1)},{passive:true})}swipe($('#viewer-area'),n=>{if(!$('#viewer-area').classList.contains('zoomed'))moveViewer(n)});
document.addEventListener('keydown',e=>{if($('#viewer').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();moveViewer(e.key==='ArrowRight'?1:-1)}});
$('#share').onclick=async()=>{const url=new URL(location.href);url.hash=current.id;try{if(navigator.share){await navigator.share({title:document.title,text:current.subtitle,url:url.href});return}if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(url.href);notify('角色链接已复制');return}}catch(e){if(e.name==='AbortError')return}$('#drawer-title').textContent='分享角色';$('#drawer-body').replaceChildren();const p=document.createElement('p');p.textContent='复制下方链接，分享这个角色。';const input=document.createElement('input');input.value=url.href;input.readOnly=true;input.style.cssText='width:100%;padding:12px;font:inherit';$('#drawer-body').append(p,input);$('#drawer').showModal();input.select()};
$('#collection').onclick=()=>{$('#drawer-title').textContent='我的收藏';const saved=chars.filter(c=>favorites.includes(c.id));$('#drawer-body').innerHTML=saved.length?saved.map(c=>`<button class="saved-row" data-saved="${c.id}"><img src="${src(c.images[0][0])}" alt=""><span>${c.name}</span></button>`).join(''):'<p>还没有收藏。轻触角色旁的爱心，把喜欢的相遇留在这里。</p>';$('#drawer').showModal()};$('#drawer-body').onclick=e=>{const b=e.target.closest('[data-saved]');if(b){location.hash=b.dataset.saved;$('#drawer').close()}};
$('#settings').onclick=()=>{$('#drawer-title').textContent='阅读设置';$('#drawer-body').innerHTML=`<label>夜间阅读<input type="checkbox" data-pref="night" ${prefs.night?'checked':''}></label><label>放大正文<input type="checkbox" data-pref="large" ${prefs.large?'checked':''}></label><label>关闭动态效果<input type="checkbox" data-pref="still" ${prefs.still?'checked':''}></label><p class="hint">收藏与阅读偏好仅保存在当前浏览器。重力感应数据仅用于本页画面位移，不上传。</p><button id="calibrate">重新校准重力视差</button>`;$('#drawer').showModal();$('#calibrate').onclick=()=>{origin=null;notify(motion?'请将手机保持在舒适角度，下一次读数会设为中心。':'先在角色页开启重力视差。')}};$('#drawer-body').onchange=e=>{if(e.target.dataset.pref){prefs[e.target.dataset.pref]=e.target.checked;setPrefs()}};$('#close-drawer').onclick=()=>$('#drawer').close();
function applyTilt(x,y){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{$('#hero').style.setProperty('--px',Math.max(-9,Math.min(9,x))+'px');$('#hero').style.setProperty('--py',Math.max(-9,Math.min(9,y))+'px')})}
function orientation(e){if(!motion||document.hidden||!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;clearTimeout(motionTimer);if(!origin)origin=[e.beta,e.gamma];const a=(screen.orientation?.angle??window.orientation??0)*Math.PI/180;const x=(e.gamma-origin[1])*.35,y=(e.beta-origin[0])*.35;applyTilt(x*Math.cos(a)+y*Math.sin(a),y*Math.cos(a)-x*Math.sin(a));$('#motion-status').textContent='重力视差已开启 · 当前角度已校准'}
function stopMotion(){motion=false;clearTimeout(motionTimer);window.removeEventListener('deviceorientation',orientation);origin=null;applyTilt(0,0);$('#motion').textContent='开启重力视差';$('#motion').setAttribute('aria-pressed','false');$('#mobile-motion').textContent='◈ 重力视差'}
async function toggleMotion(){if(motion){stopMotion();$('#motion-status').textContent='重力视差已关闭';return}if(prefs.still||reduce.matches){notify('动态效果已关闭，请先调整阅读设置或系统减少动态效果设置。');return}if(!isSecureContext){notify('请通过 HTTPS 网站开启重力视差。');return}if(!window.DeviceOrientationEvent){notify('此设备不支持重力感应，可使用鼠标视差。');return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted'){notify('未获得感应权限，可以继续静态浏览。');return}}motion=true;origin=null;window.addEventListener('deviceorientation',orientation);$('#motion').textContent='关闭重力视差';$('#motion').setAttribute('aria-pressed','true');$('#mobile-motion').textContent='◈ 关闭视差';$('#motion-status').textContent='正在等待感应数据，请轻轻倾斜手机…';motionTimer=setTimeout(()=>{stopMotion();$('#motion-status').textContent='未收到感应数据；请检查浏览器权限或换用支持的手机浏览器。'},4500)}catch{stopMotion();notify('浏览器未允许感应访问，请检查网站权限。')}}
$('#motion').onclick=$('#mobile-motion').onclick=toggleMotion;$('#open-art').addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||motion||prefs.still||reduce.matches)return;const r=e.currentTarget.getBoundingClientRect();applyTilt((e.clientX-r.left-r.width/2)/r.width*16,(e.clientY-r.top-r.height/2)/r.height*16)});$('#open-art').addEventListener('pointerleave',()=>{if(!motion)applyTilt(0,0)});reduce.addEventListener('change',()=>{if(reduce.matches)stopMotion()});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMotion();$('#motion-status').textContent='页面已暂停感应，需要时可重新开启。'}});window.addEventListener('orientationchange',()=>origin=null);
select(location.hash.slice(1));setPrefs();
