'use strict';
// 华丽扩展层：内容、顶部下拉、陀螺仪、摇一摇、星尘与波形。
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const rootStyle=document.documentElement.style;
const extras={
 haanye:{color:'#619271',relic:'晨露叶笺',place:'初芽之森',wish:'把今天的快乐，寄给明天的你。',memory:'她把最漂亮的那片叶子夹进书里，说等下次见面，要亲手交给你。',ritual:'闭上眼睛听三秒风声，再把今天遇见的一件小事记在心里。'},
 xiaoyezi:{color:'#6f9a94',relic:'碧水画册',place:'碧水庭院',wish:'愿你在安静的时刻，也能被好好陪伴。',memory:'画册翻到了新的一页。她没有说话，只把身旁的位置轻轻让了出来。',ritual:'为自己留一小段不被打扰的时间，看看天空，或者慢慢喝一杯水。'},
 twins:{color:'#9885a6',relic:'双生铃铛',place:'双生暖阁',wish:'无论白昼还是黑夜，都有人等你回来。',memory:'一只铃铛发出清脆的声音，另一只立刻回应。原来，陪伴也可以被听见。',ritual:'想起一个让你安心的人，把一句想说的感谢，认真留给对方。'},
 daidai:{color:'#6895b4',relic:'晴空星瓶',place:'晴空水镜',wish:'走得慢一点，也会抵达喜欢的远方。',memory:'她把水里的星光装进小瓶子，虽然什么也没装到，眼睛却比星星还亮。',ritual:'写下一个很小的愿望。今天只向它靠近一步，也已经很棒。'}
};
let sensorsOn=false,orientationSeen=false,motionSeen=false,lastAcc=null,lastSample=0,lastShake=-Infinity,baseline=null,pendingOrientation=null,sensorFrame=0,sensorHintTimer;
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
function haptic(pattern=[12]){try{navigator.vibrate?.(pattern);}catch{}}
function randomEncounter(){const candidates=characters.filter(c=>'character/'+c.id!==current());const c=candidates[Math.floor(Math.random()*candidates.length)];if(c){location.hash='character/'+c.id;haptic([20,35,20]);}}
function sensorLabel(){const b=document.querySelector('#sensors');b.textContent=sensorsOn?(orientationSeen||motionSeen?'✧ 感应已连接':'✧ 等待感应'):'✧ 开启感应';b.setAttribute('aria-pressed',String(sensorsOn));}
function onOrientation(e){if(!sensorsOn||document.hidden||!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;orientationSeen=true;sensorLabel();if(!baseline)baseline={beta:e.beta,gamma:e.gamma};pendingOrientation={x:clamp(e.gamma-baseline.gamma,-25,25),y:clamp(e.beta-baseline.beta,-25,25)};if(sensorFrame)return;sensorFrame=requestAnimationFrame(()=>{sensorFrame=0;if(!sensorsOn||!pendingOrientation)return;const {x,y}=pendingOrientation;window.dispatchEvent(new CustomEvent('aetheria:orientation',{detail:{x,y}}));rootStyle.setProperty('--foil-angle',`${135+x*3+y*2}deg`);rootStyle.setProperty('--foil-x',`${50+x*1.7}%`);rootStyle.setProperty('--foil-y',`${50+y*1.7}%`);if(!reducedMotion.matches){rootStyle.setProperty('--tilt-y',`${x*.22}deg`);rootStyle.setProperty('--tilt-x',`${-y*.22}deg`);rootStyle.setProperty('--aurora-x',`${x*.65}px`);rootStyle.setProperty('--aurora-y',`${y*.65}px`);}});}
function onMotion(e){if(!sensorsOn||document.hidden)return;const a=e.accelerationIncludingGravity;if(!a||![a.x,a.y,a.z].every(Number.isFinite))return;motionSeen=true;sensorLabel();const now=performance.now();if(now-lastSample<100)return;lastSample=now;const next={x:a.x,y:a.y,z:a.z};if(lastAcc){const delta=Math.abs(next.x-lastAcc.x)+Math.abs(next.y-lastAcc.y)+Math.abs(next.z-lastAcc.z);if(delta>30&&now-lastShake>2200){lastShake=now;randomEncounter();notice('星光回应了你的摇一摇 ✧');}}lastAcc=next;}
async function enableSensors(){const b=document.querySelector('#sensors');if(sensorsOn){sensorsOn=false;window.dispatchEvent(new Event('aetheria:sensors-off'));clearTimeout(sensorHintTimer);window.removeEventListener('deviceorientation',onOrientation);window.removeEventListener('devicemotion',onMotion);document.body.classList.remove('sensors-active');for(const key of ['--tilt-x','--tilt-y','--aurora-x','--aurora-y','--foil-angle','--foil-x','--foil-y'])rootStyle.removeProperty(key);sensorLabel();notice('感应已暂停，再点一次即可开启');return;}if(!window.isSecureContext){notice('感应需要 HTTPS，请在部署后的网站开启');return;}b.disabled=true;
 // 两类权限必须都在点击事件内发起，不能先 await 一项再请求另一项。
 const ask=Type=>{if(!Type)return Promise.resolve(false);try{return typeof Type.requestPermission==='function'?Type.requestPermission().then(result=>result==='granted').catch(()=>false):Promise.resolve(true);}catch{return Promise.resolve(false);}};
 const [orientation,motion]=await Promise.all([ask(window.DeviceOrientationEvent),ask(window.DeviceMotionEvent)]);b.disabled=false;if(!orientation&&!motion){notice('未获得感应权限，或浏览器不支持；可在浏览器设置中允许后重试');return;}sensorsOn=true;orientationSeen=false;motionSeen=false;lastAcc=null;lastSample=0;baseline=null;pendingOrientation=null;document.body.classList.add('sensors-active');if(orientation)window.addEventListener('deviceorientation',onOrientation,{passive:true});if(motion)window.addEventListener('devicemotion',onMotion,{passive:true});sensorLabel();notice('轻轻倾斜看流光，摇一摇邂逅角色');sensorHintTimer=setTimeout(()=>{if(sensorsOn&&!orientationSeen&&!motionSeen)notice('尚未收到感应数据，请检查浏览器权限或换系统浏览器打开');},4500);}
document.querySelector('#sensors').addEventListener('click',enableSensors);
function bindPull(){const handle=document.querySelector('#pull-handle');if(!handle)return;let start=null,dy=0,cancelled=false,suppressClick=false;
 const reset=()=>{start=null;dy=0;app.style.removeProperty('transform');app.style.removeProperty('opacity');document.body.classList.remove('pulling');handle.classList.remove('ready');};
 handle.addEventListener('touchstart',e=>{cancelled=false;suppressClick=false;if(e.touches.length!==1||window.scrollY>3)return;start={x:e.touches[0].clientX,y:e.touches[0].clientY};dy=0;document.body.classList.add('pulling');},{passive:true});
 handle.addEventListener('touchmove',e=>{if(!start)return;if(e.touches.length!==1){cancelled=true;reset();return;}const dx=e.touches[0].clientX-start.x;dy=e.touches[0].clientY-start.y;if(Math.abs(dx)>25&&Math.abs(dx)>Math.abs(dy)){cancelled=true;reset();return;}if(dy>0&&Math.abs(dy)>Math.abs(dx)*1.5){e.preventDefault();const shift=Math.min(dy*.32,95);app.style.transform=`translateY(${shift}px)`;app.style.opacity=String(Math.max(.7,1-dy/1000));handle.classList.toggle('ready',dy>85);}},{passive:false});
 handle.addEventListener('touchend',()=>{const leave=!!start&&!cancelled&&dy>85;suppressClick=cancelled||dy>10;reset();if(leave){haptic([15]);location.hash='gallery';}},{passive:true});
 handle.addEventListener('touchcancel',()=>{cancelled=true;suppressClick=true;reset();},{passive:true});
 handle.addEventListener('click',e=>{e.preventDefault();if(suppressClick){suppressClick=false;return;}location.hash='gallery';});
}
function chapterContent(){return `<section class="chapter-section"><div class="section-heading"><div><p class="eyebrow">CHAPTERS OF THE WIND</p><h2>风的四封来信</h2></div><span class="chapter-seal">VOL. 01</span></div><div class="chapter-grid">${characters.map((c,i)=>`<a class="chapter-card" href="#character/${c.id}" style="--chapter-color:${extras[c.id].color}"><span class="chapter-number">0${i+1}</span><div><small>${extras[c.id].place}</small><h3>${extras[c.id].relic}</h3><p>${extras[c.id].wish}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;}
function embellish(){app.style.removeProperty('transform');app.style.removeProperty('opacity');document.body.classList.remove('pulling');const route=current();document.body.classList.toggle('detail-open',route.startsWith('character/'));const footer=app.querySelector('footer');const insert=html=>footer?.insertAdjacentHTML('beforebegin',html);
 if(route==='home'){
 app.querySelector('.hero')?.insertAdjacentHTML('afterend',`<section class="experience-ribbon"><div><b>01</b><span>倾斜手机<br><small>让光沿着指尖流动</small></span></div><div><b>02</b><span>摇动星光<br><small>让相遇交给命运</small></span></div><div><b>03</b><span>下拉归途<br><small>从物语回到画廊</small></span></div></section>`);
 insert(chapterContent()+`<section class="letter-panel"><div class="orbit-mark" aria-hidden="true">✧</div><p class="eyebrow">A LETTER FOR YOU</p><h2>致途经此地的你</h2><p>这里没有需要赶上的时刻表。你可以停下来，听叶子讲一个小故事，和猫尾少女分享一个还没实现的梦。</p><p>愿你离开时，口袋里多一片叶子，心里多一点光。</p><span class="signature">With love, Aetheria</span><div class="actions"><button class="button" data-random>让命运选择一场相遇 ✧</button></div></section>`);
 }
 if(route==='world')insert(`<section class="panel lore"><p class="eyebrow">ORIGIN OF RESONANCE</p><h2>当第一片叶子遇见星光</h2><p>传说，幻想之境由四种温柔构成：森林的生机、庭院的安静、双生的陪伴与晴空的勇气。它们沿着看不见的叶脉，连接成同一个世界。</p><div class="timeline"><div><b>序章 · 风醒来时</b><p>一颗心愿落进晨露，初芽之森长出了第一封来信。</p></div><div><b>第一章 · 微光相认</b><p>不同的灵魂在旅途中相遇，共鸣成了彼此的路标。</p></div><div><b>下一章 · 写给你</b><p>当你打开这本物语，世界又多了一位可以分享故事的朋友。</p></div></div></section>`+chapterContent());
 if(route==='favorites')insert(`<section class="collection-progress panel"><p class="eyebrow">BONDS IN BLOOM</p><h2>羁绊正在发芽</h2><p>已与 ${favorites.size} / ${characters.length} 组角色留下心动印记</p><progress max="${characters.length}" value="${favorites.size}" aria-label="收藏完成度"></progress><small>每一份喜欢，都会在这里开成一朵小花。</small></section>`);
 if(route.startsWith('character/')){const c=characters.find(c=>'character/'+c.id===route);if(c){const x=extras[c.id];app.insertAdjacentHTML('afterbegin','<button id="pull-handle" class="pull-handle" aria-label="下拉或点击返回图鉴"><span></span><small>在此向下拉动，返回画廊</small></button>');app.querySelector('.en-name')?.insertAdjacentHTML('afterend',`<div class="resonance"><div><small>RESONANCE / 共鸣</small><span>${c.freq.toFixed(2)} Hz · 合成音色</span></div><canvas id="resonance-wave" aria-hidden="true"></canvas></div>`);app.querySelector('.story')?.insertAdjacentHTML('afterend',`<section class="relic panel"><p class="eyebrow">KEEPSAKE / 随身珍藏</p><h2>✧ ${x.relic}</h2><p>${x.memory}</p><div class="ritual"><small>今日的温柔仪式</small><p>${x.ritual}</p></div></section>`);bindPull();}}
}
window.addEventListener('aetheria:render',embellish);
// 鼠标与手机倾斜共用流光变量，不改动图片比例。
app.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||reducedMotion.matches)return;const card=e.target.closest('.card');if(!card)return;const rect=card.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;card.style.setProperty('--tilt-x',`${(0.5-y)*10}deg`);card.style.setProperty('--tilt-y',`${(x-0.5)*10}deg`);card.style.setProperty('--foil-x',`${x*100}%`);card.style.setProperty('--foil-y',`${y*100}%`);card.style.setProperty('--foil-angle',`${100+x*100}deg`);});
app.addEventListener('pointerout',e=>{const card=e.target.closest('.card');if(card&&!card.contains(e.relatedTarget))for(const key of ['--tilt-x','--tilt-y','--foil-x','--foil-y','--foil-angle'])card.style.removeProperty(key);});
app.addEventListener('click',e=>{if(e.target.closest('[data-save],[data-step],[data-random]'))haptic();const progress=app.querySelector('progress');if(progress)progress.value=favorites.size;});
// 一个动画循环，页面隐藏或系统减少动态时停止。
const dustCanvas=document.querySelector('#stardust'),dustCtx=dustCanvas.getContext('2d');let particles=[],width=0,height=0,animation=0,lastFrame=0;
function sizeCanvas(){width=innerWidth;height=innerHeight;const ratio=Math.min(devicePixelRatio||1,2);dustCanvas.width=width*ratio;dustCanvas.height=height*ratio;dustCtx?.setTransform(ratio,0,0,ratio,0,0);particles=Array.from({length:width<600?28:48},()=>({x:Math.random()*width,y:Math.random()*height,r:.5+Math.random()*1.5,s:.12+Math.random()*.22,phase:Math.random()*6.28}));}
function draw(time){animation=0;if(document.hidden||reducedMotion.matches)return;if(time-lastFrame>32){const dt=Math.min((time-lastFrame)/33,2)||1;lastFrame=time;if(dustCtx){dustCtx.clearRect(0,0,width,height);for(const p of particles){p.y-=p.s*dt;p.x+=Math.sin(time/2400+p.phase)*.12*dt;if(p.y<0)p.y=height;dustCtx.fillStyle=`rgba(147,161,111,${.22+Math.sin(time/1700+p.phase)*.15})`;dustCtx.beginPath();dustCtx.arc(p.x,p.y,p.r,0,Math.PI*2);dustCtx.fill();}}
 const wave=document.querySelector('#resonance-wave');if(wave){const w=wave.clientWidth,h=36,ratio=Math.min(devicePixelRatio||1,2);if(wave.width!==Math.round(w*ratio)){wave.width=Math.round(w*ratio);wave.height=h*ratio;}const ctx=wave.getContext('2d');if(ctx){ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#7b9b80';ctx.lineWidth=1.5;ctx.beginPath();for(let x=0;x<w;x++){const y=h/2+Math.sin(x*.09+time*.003)*Math.sin(x/w*Math.PI)*10;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}}}animation=requestAnimationFrame(draw);}
function syncAnimation(){if(animation)cancelAnimationFrame(animation);animation=0;if(!document.hidden&&!reducedMotion.matches)animation=requestAnimationFrame(draw);else dustCtx?.clearRect(0,0,width,height);}
window.addEventListener('resize',sizeCanvas,{passive:true});document.addEventListener('visibilitychange',()=>{lastAcc=null;baseline=null;syncAnimation();});reducedMotion.addEventListener('change',syncAnimation);sizeCanvas();embellish();syncAnimation();
